### ISSUE TITLE
Minor: 4.11-mp release comments have broken link

### ISSUE THREAD

**Issue by butlersrepos** [GodotSteam/MultiplayerPeer#8]
**Describe the bug**
In the release notes for 4.11-mp (https://github.com/GodotSteam/MultiPlayerPeer/releases/tag/v4.11-mp) the link to the change log is incorrect.

**To Reproduce**
1. Go to https://github.com/GodotSteam/MultiPlayerPeer/releases/tag/v4.11-mp
2. Click on '[For a full list of previous changes, please check the change-log here.](https://godotsteam.com/changelog/multiplayer-peer/)'
3. See 404 error

**Expected behavior**
The link should goto https://godotsteam.com/changelog/multiplayer_peer, the hyphen in multiplayer-peer is accidentally an underscore.

**Comment by Gramps** [comment]
Hey there!  Good find!  Thank you for reporting it!
